"""add notebook name field

Revision ID: 20d441c307e6
Revises: 8b9830f00132
Create Date: 2026-07-13 07:01:39.489946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d441c307e6'
down_revision: Union[str, Sequence[str], None] = '8b9830f00132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        # server_default backfills existing rows (you already have sessions
        # from testing) -- NOT NULL with no default would fail on those.
        batch_op.add_column(sa.Column('name', sa.String(length=256), nullable=False, server_default='Untitled notebook'))

    # Drop the server-side default after backfill -- new rows should always
    # set a name explicitly via the app (create_session), not rely on the DB.
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('name', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
